### ISSUE TITLE
version checking casing issues

### ISSUE THREAD

**Issue by Bebabo10** [Scarsz/DiscordSRV#101]
The current build of DiscordSRV is outdated! Get build 12.3 at http://dev.bukkit.org/bukkit-plugins/discordsrv/ 

will force server not to start if an old version new versions are not working

**Comment by Eufranio** [comment]
New versions are working.

**Comment by Bebabo10** [comment]
new versions aren't properly generating a config file

**Comment by Eufranio** [comment]
What's the version of your java?

**Comment by Bebabo10** [comment]
build 1.8.0_111-b15

**Comment by Scarsz** [comment]
`/discord debug`
