### ISSUE TITLE
Do not send messages to MC that are only a picture

### ISSUE THREAD

**Issue by popcorn9499** [Scarsz/DiscordSRV#108]
Discord messages that are images dont send anything other than blank lines on the minecraft chat

**Comment by 61352151511** [comment]
I've solved this issue on my Discord plugin by checking to see if the message is empty then if it is, check for attachments, if there is an attachment then the message put in Minecraft is a link. So an image is sent on Discord and a link is received on Minecraft

**Comment by mickeydarrenlau** [comment]
> I've solved this issue on my Discord plugin by checking to see if the message is empty then if it is, check for attachments, if there is an attachment then the message put in Minecraft is a link. So an image is sent on Discord and a link is received on Minecraft

How to do.

**Comment by Vankka** [comment]
> > I've solved this issue on my Discord plugin by checking to see if the message is empty then if it is, check for attachments, if there is an attachment then the message put in Minecraft is a link. So an image is sent on Discord and a link is received on Minecraft
> 
> How to do.  
This has already been solved in DiscordSRV for almost 4 years.
