### ISSUE TITLE
Bot Name and Avatar Updated based on talking Player

### ISSUE THREAD

**Issue by AaronMcHale** [Scarsz/DiscordSRV#110]
A Discord Server I'm part of that has a GMod server, they linked Discord using an ad-on, and one of the cool features this ad-on has is it changes the name and picture in chat of the Discord bot to the name and picture of the player who is talking, I'd like to have that feature for our MC Server.

I'm assuming the way they do it is send an API request to Discord to update the name and picture every time a message is sent from in-game.

Something else they have done is if you click on the name of the bot in chat it doesn't show the ranks, notes or message section that you'd normally expect to see when you click on a name just the blue section at the top that shows the name and picture of the bot at the time when it sent any given message.  The bot is also hidden from the player list down the right side of Discord.

I'm not sure how they did the above, but it would also go hand in hand with the main feature request here.

Thanks
Aaron

**Comment by Eufranio** [comment]
Probably with Webhooks, not sure how it would be in MC/Discord...

**Comment by AaronMcHale** [comment]
I'll see if I can find the code they are using

**Comment by Scarsz** [comment]
Not possible due to API restrictions
