### ISSUE TITLE
Checking account linkings

### ISSUE THREAD

**Issue by ChunkieMiner** [Scarsz/DiscordSRV#122]
Add a command that can be used on discord and ingame where you can check which player is linked to what discord account.

**Comment by Scarsz** [comment]
Why exactly?

**Comment by ChunkieMiner** [comment]
So I can check who is using that discord account in case they have a name that isn't the same as their Minecraft username

**Comment by Scarsz** [comment]
If you needed this though you could easily just open the `linkedaccounts.json` file and do a control + F for their Discord ID or Minecraft UUID. I really doubt that a player who has a linked account would bee threatening to attack the server anyway, petty shit like that is usually restricted to people who don't care about the server.

**Comment by ChunkieMiner** [comment]
I understand that I could easily do that but staff members with no file access will have to get me to do it, so it's just to make it more convenient and efficient.
