### ISSUE TITLE
Warn users that a picture was uploaded

### ISSUE THREAD

**Issue by manselis** [Scarsz/DiscordSRV#125]
This is pretty self-explanatory: images don’t show up in Minecraft but users should still be aware if something was uploaded. This feature could have a switch in the config or a command to disable/enable the messages per user.

It could be a chat message:
`DISCORD  An image was uploaded to #channelname`

Or it could be a link to the image:
`DISCORD IMAGE UPLOAD  https://example.com/link-to-image`

**Comment by Scarsz** [comment]
Already in v13; toggles per-user based on file upload permissions through Discord

**Comment by evernife** [comment]
I think an option to disable it in config should be better, this can prevent flood.

Some links has more than 3 to 4 lines.

Multiple memes can make a lot of fuz in the ingame chat.

Disable it in the discord-side will not help that much, cause it will turn more difficult to send images, and it will still have links in the chat.

**Comment by iDesiver** [comment]
> I think an option to disable it in config should be better, this can prevent flood.
> 
> Some links has more than 3 to 4 lines.
> 
> Multiple memes can make a lot of fuz in the ingame chat.
> 
> Disable it in the discord-side will not help that much, cause it will turn more difficult to send images, and it will still have links in the chat.

I do agree with what EverNife said, because its too much ingame spam with it, since (even for large monitors) it has almost 5 lines EACH link... So, I would thanks if you could make anything to help on ^-^

**Comment by Androkai** [comment]
**Suggestion**: Making use of json messages so the player only get an icon which opens the link if he clicks on.

Here is an example in form of a command to show how such a message could look like, just replace `Androkai` with your name or if you use it in a command block you can also use `@p`:
```
/tellraw Androkai ["",{"text":"Hey guys, found this epic pic"},{"text":" [","color":"dark_gray"},{"text":"⎙","color":"gold","clickEvent":{"action":"open_url","value":"https://camo.githubusercontent.com/9cc1efdcac8dbb65b27fce0fd960e9bb306484d3/687474703a2f2f692e696d6775722e636f6d2f56544a746c6c692e706e67"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Androkai","color":"aqua"},{"text":" uploaded a picture, "},{"text":"click","color":"blue"},{"text":" to open!"}]}}},{"text":"]","color":"dark_gray"}]
```
The `/tellraw` command was added with Minecraft 1.7 so it looks like this could work for all supported versions.

**Comment by iDesiver** [comment]
Yea Androkai, its a good suggestion, but how would we use it to DiscordToMinecraftChat ?

**Comment by evernife** [comment]
Seems interesting, i dont think is that hard to be done, just make a if
`
if message contain "http" replace the message with this custom json...

But i would really prefer a way to disable it.... no link for **Drag & Drop**  images

**Comment by evernife** [comment]
@Scarsz any chance to solve our problem T.T ?
