### ISSUE TITLE
Localize messages to Japanese

### ISSUE THREAD

**Issue by Scarsz** [Scarsz/DiscordSRV#140]
639-1 code is `ja`, need to modify `util/LangUtil.java` & add appropriate resource files

Only Japanese person I know is @ucchyocean, he implemented `LunaChatHook` so he'll probably be able to help out with this as his userbase coincides with ours as far as Japanese users go

**Comment by ucchyocean** [comment]
Hi @Scarsz ,
OK, I understood. Leave it to me.

**Comment by Scarsz** [comment]
Any ETA for this @ucchyocean?

**Comment by ucchyocean** [comment]
I will send PL, today or tomorrow.

**Comment by ucchyocean** [comment]
Hi @Scarsz ,
I made Japanese translation resource messages.
https://github.com/ucchyocean/DiscordSRV/commit/79b26c2399c6e72e835c069a51e59e51ecdcad93

But, something wrong. DiscordSRV cannot be loaded on ja_JP environment.
Maybe, DiscordSRV cannot handle UTF-8 encording message resource file for now.
I have to do some debug before send PL.

**Comment by Scarsz** [comment]
Any error to go with?

**Comment by ucchyocean** [comment]
Here.

[2017-03-24-1.zip](https://github.com/Scarsz/DiscordSRV/files/866243/2017-03-24-1.zip)

**Comment by Scarsz** [comment]
@ucchyocean Japanese translations seem to work fine for me, can't reproduce your issue

```
[Thu, 23. Mar 2017 15:45:07 INFO] [DiscordSRV] チャットプラグインへの接続は一つもありません
[Thu, 23. Mar 2017 15:45:07 INFO] [DiscordSRV] 色: {3498DB=, 71368A=, 95A5A6=, AD1457=, 11806A=, 206694=, 1ABC9C=, 992D22=, E67E22=, A84300=, E74C3C=, 2ECC71=, 979C9F=, 607D8B=, 99AAB5=, F1C40F=, 1F8B4C=, E91E63=, 9B59B6=, C27C0E=, 546E7A=}
```

**Comment by ucchyocean** [comment]
Oh, really?!
In my Windows10 environment, I cannot load it yet.
Which OS did you use when checking a reproduction confirmation? Windows, Macintosh, or Linux?

**Comment by Scarsz** [comment]
Windows 10 (English language, LangUtil forced to initialize as Japanese)

**Comment by ucchyocean** [comment]
Thanks.

Is it an issue specific to my environment?
I will ask other Japanese developers to do the test as well.

**Comment by Scarsz** [comment]
Specific to your environment? Don't know but I have a strong feeling that it's not. Maybe you were running an outdated dev build of DiscordSRV?

Definitely ask other Japanese developers to test the latest dev build though.

**Comment by ucchyocean** [comment]
OK, I see.
I will re-build and re-test it.

**Comment by Scarsz** [comment]
https://github.com/Scarsz/DiscordSRV/commit/79b26c2399c6e72e835c069a51e59e51ecdcad93
https://github.com/Scarsz/DiscordSRV/commit/99f91649d735ebbd324e6b171afdf5d4787c8624

**Comment by ucchyocean** [comment]
I re-built and re-tested it, but I could not load the plugin correctly yet.

It seems that the plugin is reading the message resource file with ANSI encoding. This hinders internationalization of plugins.

I sent new pull request.
https://github.com/Scarsz/DiscordSRV/pull/145
Please review this.

**Comment by ucchyocean** [comment]
Oh, your work is very quickly 👍

**Comment by Scarsz** [comment]
Go ahead and try the latest snapshot from the build server, http://scarsz.tech:8080/job/DiscordSRV/lastSuccessfulBuild/artifact/target/DiscordSRV-Build-13.0-SNAPSHOT-223.jar. If it loads good for you, Japanese translations are good to go.

**Comment by ucchyocean** [comment]
OK!
I tried 13.0-SNAPSHOT-223. It works correctly!
Thanks.

**Comment by Scarsz** [comment]
Good to hear. 😊
