### ISSUE TITLE
Command with key _ doesn't works

### ISSUE THREAD

**Issue by Nory23** [Scarsz/DiscordSRV#142]
When I use a command with the key _ the plugin doesnt read fine and can't execute the command

http://i65.tinypic.com/72u9eu.png

**Comment by Scarsz** [comment]
Please give the output of `/discord debug`

**Comment by Nory23** [comment]
https://hastebin.com/utilakacoq

**Comment by Scarsz** [comment]
This was already fixed as part of v13
