### ISSUE TITLE
Display name not being used on join

### ISSUE THREAD

**Issue by ashyon** [Scarsz/DiscordSRV#144]
I'm using EssentialsX to set the nickname of my player, but DiscordSRV shows the username on join instead of the display name. My guess is it is possible to use some Essentials API to get display name if it's installed?

**Comment by Androkai** [comment]
Have you set %displayname% here?
https://github.com/Scarsz/DiscordSRV/blob/master/src/main/resources/config.yml#L180

**Comment by ashyon** [comment]
Yes, I am using %displayname%, haven't changed then from the default

**Comment by Androkai** [comment]
Do you also have this set to `true` in EssentialsX's config.yml?
https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/config.yml#L36

**Comment by ashyon** [comment]
Yes, and it works for the leave command. Guessing it sets the display name after the join message is sent to discord?

**Comment by Scarsz** [comment]
Already fixed on v13
