### ISSUE TITLE
Legacy plugins have been broken

### ISSUE THREAD

**Issue by EricRabil** [Scarsz/DiscordSRV#149]
By removing the latestbuild file, all plugins running legacy versions have been broken due to the link 404ing when the plugin tries to check it.

**Comment by Scarsz** [comment]
Side effect of advancement.

**Options:**

1. Update to the latest version (13.2 at the moment). Gain lots of new features and security fixes. **Highly recommended.**
2. Stick to old versions by adding `UpdateCheckDisabled: true` to the `config.yml`. I don't suggest you do this.

**Comment by EricRabil** [comment]
My implementation of DiscordSRV is a heavily modified of 8.2 (I think?) So I'll take a look at added features and drop them in, I guess

**Comment by Scarsz** [comment]
The entire plugin was rewritten for v13. Nothing is drag and drop, sorry. If you have features you want added to DiscordSRV, feel free to submit them via a pull request.
