### ISSUE TITLE
Add uChat (aka UltimateChat) hooks

### ISSUE THREAD

**Issue by klennan** [Scarsz/DiscordSRV#155]
https://dev.bukkit.org/projects/uchat
https://dev.bukkit.org/projects/uchat/pages/uchat-api-pt-br
Sorry it's in Portuguese, but Google does translate it nicely.

**Comment by Androkai** [comment]
Seems like the API is missing some kind of function to send a message to a channel or get all players listening to a channel so we can handle it. I only found an event I can listen for messages coming from UChat.
Also found this API request: https://github.com/FabioZumbi12/UltimateChat/issues/9

**Comment by klennan** [comment]
PurpleIRC recently added the uChat hooks. Hope this helps:
https://github.com/cnaude/PurpleIRC-spigot/commit/fba98f6aee4beefbf066216ec218fabf9eda8b21

**Comment by Androkai** [comment]
Didn't really help but thx for the hint. It's between from the same guy (cnaude) who made the request I found because he also seems to have had the problem that receiving is no problem to implement but sending is a mess.

**Comment by klennan** [comment]
What if you were to add code to at least send uChat chat to Discord, by channel name? That, plus having a permission per channel for chat from Discord would sort out who sees it in Minecraft. We wouldn't necessarily need DiscordSRV to target a uChat channel.

**Comment by Androkai** [comment]
For sure there is always a possible solution but to be honest, your suggestion is very bad practice and it's not our job to fix this. We try to deliver a highly customize-able stable product and from time to time we have to decide things like that to not continue other peoples faults so please understand this. As soon as a better possibility was made we will try to implement this into DiscordSRV.
