### ISSUE TITLE
DiscordChatChannelColorTranslations not showing a costum defined color.

### ISSUE THREAD

**Issue by q220** [Scarsz/DiscordSRV#156]
So I am using this custom color on Discord, defined by hex value #55FFFF which should translate to &b (cyan) in Minecraft. However when I added it to the DiscordChatChannelColorTranslations it shows up as white/default in the game chat.

config.yml: https://gist.github.com/q220/70bc8694631d66e87c7a5b6061ed767f
messages.yml: https://gist.github.com/q220/2dd3ae5b1e62a09a7929c2375ac8efbd

**Comment by Scarsz** [comment]
Known bug already fixed on develop
