### ISSUE TITLE
Discord -> Minecraft Role Sync

### ISSUE THREAD

**Issue by clovisd** [Scarsz/DiscordSRV#160]
Hey!

Would it be possible to have DiscordSRV sync ranks in the opposite direction?

So instead of Syncing discord ranks with in-game ranks,  it could sync it backwards. Taking the Discord roles and assigning ranks in game (through Vault?)  based on that. Possibly setting the highest Discord rank as their primary and then all other ranks as secondary groups.

Thanks!

**Comment by Scarsz** [comment]
This was discussed before MC -> Discord was added and it was concluded that
MC -> Discord was much more wanted than the other way around. It doesn't
really work logistically either, it's much easier to see what groups
someone is in to sync than to set the groups their groups. It's just a lot
more complicated to do it.

**Comment by clovisd** [comment]
So I'm taking that is a no? Or just a 'there wasn't enough demand for a bridge in the opposite direction?" so we didn't implement it?

If so, please close this issue.

**Comment by StargateMC** [comment]
@Scarsz Just throwing it out there, allowing Discord -> Minecraft role sync allows for any discord-integrateable service (eg: Patreon) to assign roles, and therefore ingame ranks.

**Comment by Vankka** [comment]
This is a duplicate of https://github.com/DiscordSRV/DiscordSRV/issues/326

This will be added, in DiscordSRV V2 (Eta this summer)
