### ISSUE TITLE
Error catching

### ISSUE THREAD

**Issue by NichtDerBert** [Scarsz/DiscordSRV#162]
Hi there,
the plugin spamms the console when lost connection to discord and cant reconnect or get an unknow response, looks like this: https://pastebin.com/ni315jgh

Is there a way for you to catch this error and just output "Connection to discord lost" or something else in the console? Would be nice :) and wont spam the console.

otherwise very nice plugin

**Comment by Scarsz** [comment]
I complained to @DV8FromTheWorld about this a while ago, the current error should be a debug-level message with the error being a user-friendly one, I don't think anything's been changed though. Either way, I already did a couple things to dramatically shorten JDA's error messages completely, it'll be in v12.4 when it's released or you can get the latest dev build.

**Comment by DV8FromTheWorld** [comment]
O.o when did we talk about this lol.

**Comment by Scarsz** [comment]
We didn't talk about it directly; I went to JDA's Discord server and bitched for a little bit. You only responded with one message.

**Comment by DV8FromTheWorld** [comment]
I don't remember this at all to be honest. Open an issue on the JDA github.

**Comment by Scarsz** [comment]
Do a search in the JDA server `from` me, will show my messages from then. Haven't said anything there since.

Opened an issue though; https://github.com/DV8FromTheWorld/JDA/issues/304
