### ISSUE TITLE
Deprecated Event Warning

### ISSUE THREAD

**Issue by bittiez** [Scarsz/DiscordSRV#163]
"DiscordSRV v13.3" has registered a listener for org.bukkit.event.player.PlayerAchievementAwardedEvent on method "public void github.scarsz.discordsrv.listeners.PlayerAchievementsListener.PlayerAchievementAwardedEvent(org.bukkit.event.player.PlayerAchievementAwardedEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [Scarsz & Androkai].

This was in my console

**Comment by Androkai** [comment]
It's because Achivements will be removed in the future of Minecraft and Discord is working with them. We already fixed this in our development branch. Nevertheless, thank you for the report. 👍
