### ISSUE TITLE
Add bPermissions support.

### ISSUE THREAD

**Issue by KarlOfDuty** [Scarsz/DiscordSRV#169]
bPermissions support for group synchronization would be nice as it is widely used and integrates well with other plugins. Also, adding a list of which permission plugins are supported would be nice as I could not find one.

**Comment by Scarsz** [comment]
https://github.com/Scarsz/DiscordSRV/tree/master/src/main/java/github/scarsz/discordsrv/hooks/permissions

**Comment by KarlOfDuty** [comment]
Thanks for the list. Is it possible bPermissions support may be implemented in the future or should I switch to one of the plugins on the list?

**Comment by Scarsz** [comment]
Merging with #177, integrating with specific permissions plugins is going to be dropped and replaced with the person simply having a permission or not.
