### ISSUE TITLE
Add send message to discord to api

### ISSUE THREAD

**Issue by bittiez** [Scarsz/DiscordSRV#171]
It would be nice for other plugins to be able to use the API to send messages to discord, I've got a plugin that responds to players in chat about questions they may ask, or whatever the owner sets up, and I would love for it to listen to discord(already possible) and be able to send messages to discord through the api as well.

**Comment by MaxiMiniJaniJos** [comment]
Just use the JDA api.

**Comment by Scarsz** [comment]
Use the DiscordUtil class, it has static methods in there for everything related to Discord
