### ISSUE TITLE
Add way to temporarily not send console to discord.

### ISSUE THREAD

**Issue by Goofables** [Scarsz/DiscordSRV#174]
The other day I had to do some things that produced a lot of spam to the console and outputted some sensitive data. I would like a way to temporarily stop sending the console to discord without disabling the whole plugin. For example '/discord send' to toggle.

**Comment by Scarsz** [comment]
Temporarily toggle the bot's `send message` permission for the channel

**Comment by Goofables** [comment]
But that spamms the server console even more.

**Comment by Scarsz** [comment]
Disable DiscordSRV for a second then.
