### ISSUE TITLE
add a feature to disable join and quit messages overall.

### ISSUE THREAD

**Issue by MaxiMiniJaniJos** [Scarsz/DiscordSRV#175]
Hey,

Someone came with the question if he could disable the join and quit messages. Then I found out that it actually wasn't possible as a feature. You could but you or had to give -discordsrv.silentjoin/silentquit to the default group or set the join and quit message to blank. Maybe it would be nice to make a feature for it.

Just add something like this to config
EnableJoinMessages: true
EnableQuitMessages: true

LemmoTresto.

**Comment by Scarsz** [comment]
Yes it is. Make the messages for them in messages.yml blank.
