### ISSUE TITLE
Add the ability to change every message of the plugin

### ISSUE THREAD

**Issue by T1MOXA** [Scarsz/DiscordSRV#193]
Add the ability to change every message of the plugin
Like:
Your link code is {code}. PM the bot on Discord ({botname}) containing just this code as the message to link your accounts.

**Comment by Scarsz** [comment]
No reason

**Comment by T1MOXA** [comment]
But what about customization and custom translation ?

**Comment by Scarsz** [comment]
You can make a translation for any other languages and I'll gladly add it in to DiscordSRV.
