### ISSUE TITLE
Private channels are broadcasted to Discord

### ISSUE THREAD

**Issue by DraksterAU** [Scarsz/DiscordSRV#2]
Can you please either implement a single ingame channel for discord broadcasts or create a blacklist of channels that cannot be broadcasted...

Faction/Allies channels, Town / Nation channels etc shouldn't be broadcasted to the whole server...

**Comment by Scarsz** [comment]
Nothing I can do about this other than individually check each and every plugin that I would have to define individually for whether or not the message can be shown. More the plugin's fault for not cancelling the message as far as I'm concerned.

**Comment by DraksterAU** [comment]
@scarsz You have no chat channel support actually? Through vault perhaps?

Channels are handled through plugins like vault and register I believe. If you call raw chat messages it will just get everything and it's by design... 

I could be wrong, but I'm pretty sure I'm not :P

Maybe look at the source from bukkitspeak for inspiration? I'll do the same and see if I can help.

**Comment by Scarsz** [comment]
Fixed in next build

**Comment by DraksterAU** [comment]
@Scarsz Thanks man, Appreciated. We can finally kill of TS3 :D

**Comment by Scarsz** [comment]
Be sure to join the Discord channel for a notification when it's ready

**Comment by DraksterAU** [comment]
Which channel @Scarsz ?

**Comment by Scarsz** [comment]
https://discord.gg/0kyJX9eYcsFbz4pJ
