### ISSUE TITLE
Command to update someone's role on Discord

### ISSUE THREAD

**Issue by Pawned** [Scarsz/DiscordSRV#200]
Now that users are able to link their MC Account to their Discord one it would be good if there was a command to be able to change someone's role on Discord.

My main reasoning for this is that I have roles on my Discord server for donators and it would be cool if when someone donates that the server could automatically send a command to DiscordSRV to promote the user on Discord.

**Comment by MaxiMiniJaniJos** [comment]
Use group role synchronisation

**Comment by MaxiMiniJaniJos** [comment]
when someone donates you use a permissions plugin to give them a new group right?
there's a feature to sycnhronise groups to roles. You give the person a permission and discordsrv will add the role.
Look in the config at line 203 and 204

**Comment by Pawned** [comment]
Yep my bad I overlooked that, thanks :)
