### ISSUE TITLE
Strip util striped not color words.

### ISSUE THREAD

**Issue by david50407** [Scarsz/DiscordSRV#210]
In `strip` method ( [src](https://github.com/Scarsz/DiscordSRV/blob/master/src/main/java/github/scarsz/discordsrv/util/DiscordUtil.java#L108) ), the string with ANSI color code will be strip.

But the regex rule is wrong, here's a fix:

```
\\[[0-9]{1,2};[0-9]{1,2};[0-9]{1,2}m
\\[[0-9]{1,3}m
[m

to

\e\\[[0-9]{1,2};[0-9]{1,2};[0-9]{1,2}m
\e\\[[0-9]{1,3}m
\e[m
```

Notice that leading `\e` (ANSI escape).

Without capturing `\e`, this method will strip `[memo]` to `emo]`, but this is not color code.

**Comment by Scarsz** [comment]
The text where `[m` would be stripped isn't part of an ANSI sequence
