### ISSUE TITLE
Plugin wont start.

### ISSUE THREAD

**Issue by Jager67** [Scarsz/DiscordSRV#228]
Server Jar: Thermos-1.7.10-1614-57-server
Mod Pack: Project Ozone 2
Plugin Jar: DiscordSRV-Build-14.8
Error: https://pastebin.com/DuDWjbuW

**Comment by MaxiMiniJaniJos** [comment]
The **SpecialSource** library included with Thermos uses ASM**4**.
Updating it to the latest version will fix the issue.

**Instructions for updating to ASM5:**
**1**. Navigate to the `libraries\net\md-5\SpecialSource\1.7-SNAPSHOT` folder of the server
**2**. Delete the `SpecialSource-1.7-SNAPSHOT.jar` jar file
**3**. Download SpecialSource v1.7.4 from http://central.maven.org/maven2/net/md-5/SpecialSource/1.7.4/SpecialSource-1.7.4.jar
**4**. Copy the jar file to the `libraries\net\md-5\SpecialSource\1.7-SNAPSHOT` folder
**5**. Rename the jar file you just copied to `SpecialSource-1.7-SNAPSHOT.jar`
