### ISSUE TITLE
Allow DiscordChatCommands->MC but not DiscordChat->MC

### ISSUE THREAD

**Issue by YourMCAdmin** [Scarsz/DiscordSRV#232]
I'm working on a series where people are able to run certain commands in a Discord chat room as well as talking to each other like a normal chat room. The commands are then run as console commands in Minecraft. 

However, I set DiscordChatChannelDiscordToMinecraft to false because I didn't want the chat showing up in game. When I disabled DiscordChatChannelDiscordToMinecraft, I found out that I can't run DiscordChatChannelConsoleCommands.

Is it possible to add a feature allowing ChatChannelConsoleCommands while keeping ChatChannelDiscordToMinecraft disabled? 

Thanks!

**Comment by Scarsz** [comment]
Should be fixed https://github.com/Scarsz/DiscordSRV/commit/75740829f0719cff08a9264cf39648ce8b103a31
