### ISSUE TITLE
Channel topic updates too frequently.

### ISSUE THREAD

**Issue by jhgg** [Scarsz/DiscordSRV#238]
Hi!

Developer from @hammerandchisel here. We are noticing a lot of people using this plugin. It's a bit aggressive as to the frequency it updates the channel topic. Doing it every few seconds. We don't want to ban people using this plugin, the rate at which this plugin updates the channel topic constitutes a breach of our API Terms of Service - namely, section 2.7 

>2.7 Rate Limits. You will not attempt to exceed or circumvent limitations on access to and use of the SDK or API, exceed or circumvent any limitation on the API calls you may make, or otherwise use the SDK or API in a manner that exceeds reasonable request volume, or constitutes excessive or abusive usage (“Rate Limits”). If Discord, in its sole discretion, determines that you have attempted to exceed or circumvent Rate Limits, or other controls that limit use of the SDK or API, then your ability to use the SDK or API may be temporarily suspended or permanently blocked.

As we consider this excessive or abusive usage of our APIs. If you could increase that timer to 5 to 10 minutes (the longer between updates the better), it'd be greatly appreciated. We don't want to have to continue banning users of this plugin from our platform for API misuse.

Thanks!

**Comment by Scarsz** [comment]
Rate of channel topic updates will be set to a minimum of 5 minutes per channel, thank you for an official say on this.

**Comment by Scarsz** [comment]
Has been addressed with https://github.com/Scarsz/DiscordSRV/pull/239/commits/2f9e19af3874a348a0b036ed50c65a136d0c766a and v15.2 has been uploaded to the distribution centers. Thanks a bunch for the issue, @jhgg.
