### ISSUE TITLE
Verified players when kicked from discord can no longer re-verify. 

### ISSUE THREAD

**Issue by FrozenBeard** [Scarsz/DiscordSRV#240]
If a player verifies themselves in-game, so they are set to a new role on discord automatically, if they are kicked from discord channel for spamming or whatever, when they come back they are the default role, and cant re-verify.

**Comment by Scarsz** [comment]
What? Are you saying that if a person gets kicked from the Discord server, rejoins, logs in on the Minecraft server, they do not get their roles set again? I see no way this would be possible as the group synchronization doesn't rely on the person being a member of the Discord server or not, it just keeps user IDs.

**Comment by FrozenBeard** [comment]
I think you misread, If they get kicked from **Discord** server, rejoins the **DISCORD** server, their role on the **DISCORD** server that was set when they verified themselves has been removed, since they re-join the **DISCORD** server their role on the discord server was reset to the default. They can not re-verify from the minecraft server as they have already done so.

**Comment by Scarsz** [comment]
I didn't misread. If they want their Discord roles back, all they need to do is rejoin the Minecraft server.

**Comment by Androkai** [comment]
Sounds like you use `MinecraftDiscordAccountLinkedRoleNameToAddUserTo`. If so sure, your users first needs to `/discord unlink` and `/discord link` again. To prevent them from doing so use `GroupRoleSynchronizationRoleIdsToSync`. Booth can be found in config.yml.

**Comment by FrozenBeard** [comment]
@Androkai I haven't allowed users to unlink, as I have some commands run when they link, I don't want them to be able to spam link/unlink. 
I don't have GroupRoleSynchronizationRoleIdsToSync my config must be outdated! Ill update discordSRV and add it.
