### ISSUE TITLE
multichat | chat messages are not sent to discord

### ISSUE THREAD

**Issue by KonoromiHimaries** [Scarsz/DiscordSRV#241]
https://github.com/MultiChat/Development/issues/19

**Comment by florian262000** [comment]
Hi!
Do you have a Solution for this Problem? I have the same Problem at the Moment. 
Thx for your Response.

**Comment by Scarsz** [comment]
MultiChat is based on BungeeCord while DiscordSRV is based on Bukkit. They're not compatible.
