### ISSUE TITLE
DiscordSRV fails to fetch URL on startup

### ISSUE THREAD

**Issue by TheRealPear** [Scarsz/DiscordSRV#242]
Console log: https://hastebin.com/gozevisafo.pas
Edit: This appears after the first message: `[Warn] [DiscordSRV] Failed to check against minimum version of DiscordSRV: received minimum build was not 40 characters long & thus not a commit hash`

I apologize if this was posted before, but I was wondering if there was a way to fix this?

**Comment by MaxiMiniJaniJos** [comment]
This is not a problem, just ignore it.

**Comment by patricktsidina** [comment]
Is it possible to disable this error message? or at least change it to warning?

**Comment by Vankka** [comment]
No, it's a error, not a warning. The only way to disable that is disabling the update checker, which has security consequences
