### ISSUE TITLE
[General Question] (possible issue) Console Via Chat Channel

### ISSUE THREAD

**Issue by bigbluu722** [Scarsz/DiscordSRV#246]
Q: How would one go along adding a specific user to the config of the plugin to allow the usage of sending a command to the console from the chat channel? (If that's possible)

Possible issue: 
I have a roll on the discord that's supposed to be able to use console, but it seems to be denying access due to the fact that I have 2 other roles above it.

**Comment by Scarsz** [comment]
This is better done as a ticket on our Discord server https://scarsz.me/discord
