### ISSUE TITLE
How do i can create a Two room in One server?

### ISSUE THREAD

**Issue by mat41997** [Scarsz/DiscordSRV#252]
I dont can create a console channel and normal chat channel separate in other discord channel?

**Comment by Andre601** [comment]
You can define a console-channel in the config.yml
Just read everything carefully there...

**Comment by Androkai** [comment]
Please give us more information about what you did and what you want to do. You're also welcome to visit our [Discord server](https://scarsz.me/discord) to get fast help with your DiscordSRV related problems.

**Comment by mat41997** [comment]
my discord https://discord.gg/bYc6JPY

my timings https://timings.aikar.co/?id=c7a4a6b4e63e4c008c6792065360d3b0

my config
https://gist.github.com/mat41997/2e2bda49951ce47e4e6807fba0e7972d

**Comment by Scarsz** [comment]
We don't care about any of that. Join ***OUR*** Discord server to get help for this.

**Comment by mat41997** [comment]
ok. thanks now work : D
