### ISSUE TITLE
Changing status of bot

### ISSUE THREAD

**Issue by FrankHeijden** [Scarsz/DiscordSRV#259]
Heya, i'd like to request a feature to change the status of the discord bot.
E.g. changing it to Do Not Disturb.

Also, i'd like to see a feature where we can enable certain discord groups which may be mentioned such as a moderator group.

**Comment by Scarsz** [comment]
No point

**Comment by FrankHeijden** [comment]
Thats why its an enhancement xD and the mentioning a group has a point lol

**Comment by Scarsz** [comment]
It's not an "enhancement" if it's an utterly pointless, useless addition. Group mentioning has already been fixed.
