### ISSUE TITLE
uChat integration not working

### ISSUE THREAD

**Issue by evernife** [Scarsz/DiscordSRV#261]
`[DiscordSRV - Initialization/ERROR]: [DiscordSRV] Plugin DiscordSRV v15.4 has failed to register events for class github.scarsz.discordsrv.hooks.chat.UltimateChatHook because br/net/fabiozumbi12/UltimateChat/API/SendChannelMessageEvent does not exist.`

**Comment by Scarsz** [comment]
Update UltimateChat

**Comment by Eufranio** [comment]
DiscordSRV is outdated, not uchat. It updated the API some time ago.
