### ISSUE TITLE
Feature Request - Listen to commands

### ISSUE THREAD

**Issue by jonassvensson4** [Scarsz/DiscordSRV#263]
Hey!

It would be awesome if you could configure the plugin to listen to certain commands.
If someone writes /help for example I could add that command in the config and then it will alert the admin role on Discord with the @role.

**Comment by Scarsz** [comment]
I really feel like this would be better done in the appropriate plugins. Maybe a `/helpop` replacement that implements DiscordSRV?

**Comment by Scarsz** [comment]
Track #257 for when a `/report` command is added
