### ISSUE TITLE
Suggestion: Store Linked accounts in a MySQL Database.

### ISSUE THREAD

**Issue by PenguinNexus** [Scarsz/DiscordSRV#265]
I would like the Linked accounts to be stored in a MySQL database rather than a JSON file. Please obviously have this as an option, not forced, but for those with a MySQL database like me, I can integrate it with other Web Services in order so my Server's Support Team can look/edit the data. It would also allow for easy editing online without having to go into server files.

**Comment by Scarsz** [comment]
https://github.com/Scarsz/DiscordSRV/issues/189
