### ISSUE TITLE
The bot wont set channel topics?

### ISSUE THREAD

**Issue by zackern** [Scarsz/DiscordSRV#267]
The problem:
Suddenly the bot stops setting the channel topics for both chat channel and console channel.
I don`t know if I have changed something that made this happen but I don´t THINK so.

When I stop the server I get this error: https://h.gnien.no/xehapotezi

The output from /discord debug: https://gist.github.com/anonymous/a88d2cb47270620c5dc1ad3d1fd5bd5c

**Comment by Scarsz** [comment]
should be fixed with https://github.com/Scarsz/DiscordSRV/commit/43599b3033177a4f0381bfde887769fc25837cff
