### ISSUE TITLE
[Request] Support Rich Presence to display game-data for players.

### ISSUE THREAD

**Issue by FrozenBeard** [Scarsz/DiscordSRV#273]
https://www.youtube.com/watch?v=Ss-IvNjl7JQ

**Comment by VankkaGithub** [comment]
Not implemented in JDA (https://github.com/DV8FromTheWorld/JDA) yet

**Comment by FrozenBeard** [comment]
Lame

**Comment by Scarsz** [comment]
Not possible for the bot to set other people's game statuses, for having the bot show it's own rich presence see #300

**Comment by gerd2002** [comment]
With the forge version this might be possible.
