### ISSUE TITLE
Can't set discord admin's nickname

### ISSUE THREAD

**Issue by jonthesquirrel** [Scarsz/DiscordSRV#275]
When I do /discord link, in console it says:
Could not set nickname for <my user info> because "Can't modify a member with higher or equal highest role than yourself!"

Is this because I'm an admin on the discord?

**Comment by gerd2002** [comment]
This is related to the Discord Permission system. If you are the owner, there is no way for the bot to nick you. If you are "just" an admin, ask the owner to put the bots role higher than the admins role.

**Comment by jonthesquirrel** [comment]
Thanks, that makes sense. Yep I'm an owner, and I put the bot role higher than the admin role.
