### ISSUE TITLE
The provided token is invalid!

### ISSUE THREAD

**Issue by Starystars67** [Scarsz/DiscordSRV#276]
Hi, after following the installation instructions and getting DiscordSRV to work with my minecraft (spigot 1.12.2) DiscordSRV now fails to work with the following issue: 
![image](https://user-images.githubusercontent.com/15389482/33069407-5e5f245a-ceac-11e7-98a5-739ef6d86037.png)
"The provided token is invalid!" so based upon this i tried recreating the bot and reinstalling everything however this has failed to solve this issue, has a dependency for this failed somewhere?

Thanks for any help anyone can provide

**Comment by Androkai** [comment]
Like the message said your Bot-Token is invalid. Make sure you created a bot user so it's really a bot token and not the client id. Then put the correct one into config.yml and try again.

**Comment by Starystars67** [comment]
Hi Androkai, I did put the bot token in the config.yml see image: 
![image](https://user-images.githubusercontent.com/15389482/33070986-b79434d4-ceb1-11e7-97e7-9ba27441f31f.png) as you can see i did use the bot-token and not the client id
![image](https://user-images.githubusercontent.com/15389482/33071032-e9ac4786-ceb1-11e7-9f94-94194a62abff.png)
Thanks for your help, any other ideas? unless i am miss understanding you?

**Comment by Androkai** [comment]
Looks good. With an actual valid token it should definitely work.

**Comment by Androkai** [comment]
If not check that your config.yml is encoded in UTF-8, this could probably be a problem if not.
![image](https://user-images.githubusercontent.com/3952718/33071370-8dc7b87e-cebb-11e7-9835-81e0be557493.png)

**Comment by Starystars67** [comment]
So my bot token is correct and i just checked the encoding and it was UTF-8 so that isnt the issue, and just restarted the plugin and still the same issue, is it possible that Rich Presence is causing an issue?

**Comment by Androkai** [comment]
The error message is very precise. The string with which the bot tries to log on to the Discord servers is invalid. So no, no problem with rich presence.

Do you upload the files to a server afterwards? In that case, please check if they arrive safely. Otherwise I'm running out of ideas. Use `/discord debug` and send us the output. Maybe @Scarsz has another one.

**Comment by Starystars67** [comment]
yes i was uploading them and i double checked all was transfering correctly, i did the command and here is the link: https://gist.github.com/anonymous/cacaea027c3c160ae6a5da2977520b46#file-1-discordsrv-info-txt-L2

**Comment by Androkai** [comment]
For some reason the redaction of your bot token doesn't worked. Please regenerate your token to be one the safe side. I recommend a full server restart instead of using PlugMan because the instance of JDA (Discord API DiscordSRV is using) probably isn't correctly terminated/recreated this way.

**Comment by Scarsz** [comment]
yeah, we don’t support the plugin in the case of plugman tampering for a reason

**Comment by Starystars67** [comment]
Well that's strange last restart was when i noticed the issue, but its working now. Thank you!
