### ISSUE TITLE
Private messaging system

### ISSUE THREAD

**Issue by Eufranio** [Scarsz/DiscordSRV#28]
Implement a private message system, like:

In the server, a person use /dtell <Discord username or nick> <message>
And the bot account, in Discord, sends the message in private to the <user>.

On Discord, a person sends a private message to the bot like !tell <minecraft username> <message> and the message is sent to the player in-game.

**Comment by Androkai** [comment]
Ideas for private messaging system:
Now you're able to send private messages from Discord to Minecraft by sending a private message to the bot using !msg <MCplayername> <message>. Ingame users are able to answer to the latest message by using /discord reply <message> or sending messages to other linked users by using /discord msg <username#1234> <message> (you can use auto completion of Discord-usernames by using Tab-key).
Writing from ingame to non-linked Discordusers is only allowed with special permission to prevent spamming. Possible additions are muting of users/players within Minecraft or Discord. Writing with non-linked accounts from Discord to Minecraft isn't intended.

Commands:
/discord link <username#1234>
/discord linklist - show all Discord-accounts linked with this one
/discord unlink <username#1234/all> - remove link for specific/all Discord-accounts
/discord reply <message> or short /discord r <message or shorter /dr <message>
/discord msg <username#1234> <message> or /discord pm ... or /discord tell ... or /dmsg ... or ...

!link <mcname>
!unlink <mcname>
!msg <playername> <message> or !pm <playername> <message>
!list
