### ISSUE TITLE
Issue: Localization problems!

### ISSUE THREAD

**Issue by ElandaOfficial** [Scarsz/DiscordSRV#288]
Hey, there's a problem with the localization!
Whenever the bot sends you a private message, the message is in german instead of english and I can't find a way to change this.
Also, when the account gets unlinked, the unlink message on the MC-Server is also in german!

Elanda

**Comment by Scarsz** [comment]
Specify `en` for `ForcedLanguage` ((https://github.com/Scarsz/DiscordSRV/blob/master/src/main/resources/config/en.yml#L26)) if you'd like to ignore the environment variable and force English
