### ISSUE TITLE
Request: In-game Discord Bot Commands

### ISSUE THREAD

**Issue by tomkeuper** [Scarsz/DiscordSRV#292]
Hello, 

I would like a option to be able to send Discord commands via the in-game chat.
like: !skip (in minecraft) then !skip (in Discord)
so you can skip songs from minecraft itself. I know this will be difficult, if possible (idk). Because bots normaly only accept commands from players in the voice channel it is playing in. 

Thanks!

**Comment by Fratik** [comment]
@tomkeuper this **probably** is not possible. You could make your bot trigger commands by changing line 50 of messages config to just `%message%`, but:
1. Most of the bots are ignoring other bots' messages.
2. I don't think that is possible for your DiscordSRV bot to connect to a VC. It could be, but how would you provide it to Minecraft for the bot to connect? Yah, as I said, I don't think that's possible.

Remember that I'm not the developer and this are only my thoughts.
Cheers!

_sorry for my bad English_

**Comment by VankkaGithub** [comment]
^^
2. Yeah you basicly couldn't even do it with the api: https://github.com/Scarsz/DiscordSRV/blob/master/src/main/java/github/scarsz/discordsrv/DiscordSRV.java#L315

**Comment by MaxiMiniJaniJos** [comment]
1. If a bot does not ignore another bot then it's a pretty bad bot.
2. It's possible for a bot to join a voice channel but with point 1 being in the way for every major bot it's just not going to work.

**Comment by tomkeuper** [comment]
@Fratik I'm using the rhythm bot for music. And it only accepts commands when you are in the same voice channel as him.
So if the bot could join a voice channel and then via an in-game command you could enter something with no prefixes or anything I think it could be possible

**Comment by Scarsz** [comment]
Won't be done
