### ISSUE TITLE
Chat gets cut off

### ISSUE THREAD

**Issue by BlackAce21** [Scarsz/DiscordSRV#295]
If a message is too long in discord it gets cut off ingame. Suggest adding a character count and splitting the string into multiple messages if the first is too long to display in one ingame message. :)

**Comment by Androkai** [comment]
Set [`DiscordChatChannelTruncateLength`](https://github.com/Scarsz/DiscordSRV/blob/master/src/main/resources/config/en.yml#L54) to 2000 (which is Discord's limit) to get what you want.
