### ISSUE TITLE
PEX group -> Discord role not working

### ISSUE THREAD

**Issue by StrideyGH** [Scarsz/DiscordSRV#302]
PEX group and Discord role won't sync.
`GroupRoleSynchronizationRoleIdsToSync: ["408340064406339585"]
GroupRoleSynchronizationCycleTime: 5
GroupRoleSynchronizationRemoveRolesOnUnlink: true`

**Comment by Scarsz** [comment]
GitHub issues is not the proper place to seek support. See #support in https://scarsz.me/discord for help.
