### ISSUE TITLE
16.0 broke UltimateChat integration

### ISSUE THREAD

**Issue by TrademarkTM** [Scarsz/DiscordSRV#304]
Title says it all.
The messages from the plugin simply aren't displayed on the channel. No errors in console.

I'm using 16.0 and UChat 1.8.5 (lastest)...
I really don't get the problem.

- The chat is properly configured, also the bot gets online and the leave, death and join messages show up normally.
https://gist.github.com/anonymous/430bcb9fa907275eae8bfb0a7995a335

Had this other error recently: 
```03.02 09:57:26 [Server] ERROR [DiscordSRV] DiscordSRV failed to load properly: org.bukkit.configuration.MemorySection cannot be cast to java.lang.String. We've made a debug report with useful information, report your issue and provide this url: https://gist.github.com/fad86b744c3c9cf4d4f89c83bd1da175```

**Comment by Scarsz** [comment]
Your chat is absolutely **not** properly configured. Referencing https://gist.github.com/anonymous/430bcb9fa907275eae8bfb0a7995a335#file-3-config-yml-L11, you supposedly have a channel in Minecraft called `global.yml` which you almost certainly don't.

Your secondary error is a problem of you making a config value a list where it is only acceptable as a string.
