### ISSUE TITLE
Ultimate Chat

### ISSUE THREAD

**Issue by TimRambo** [Scarsz/DiscordSRV#308]
i use build 16.0

> 05.02 01:48:19 [Server] ERROR [DiscordSRV] Plugin DiscordSRV v16.0 has failed to register events for class github.scarsz.discordsrv.hooks.chat.UltimateChatHook because br/net/fabiozumbi12/UltimateChat/Bukkit/API/SendChannelMessageEvent does not exist.

> 05.02 01:48:57 [Server] INFO CONSOLE issued server command: /list 

> 05.02 01:49:13 [Server] ERROR [DiscordSRV] [JDA] One of the EventListeners had an uncaught exception

> 05.02 01:49:13 [Server] ERROR [DiscordSRV] [JDA] java.lang.NoClassDefFoundError: br/net/fabiozumbi12/UltimateChat/Bukkit/UChat

gonna bet its an ultimate chat issue
write to me and tell me another chat plugin i can use that actually works.

**Comment by Scarsz** [comment]
The two classes you've given errors for are both available in the UltimateChat repo.

`br.net.fabiozumbi12.UltimateChat.Bukkit.API.SendChannelMessageEvent`: https://github.com/FabioZumbi12/UltimateChat/blob/master/UltimateChat-Spigot/src/main/java/br/net/fabiozumbi12/UltimateChat/Bukkit/API/SendChannelMessageEvent.java

`br.net.fabiozumbi12.UltimateChat.Bukkit.UChat`: https://github.com/FabioZumbi12/UltimateChat/blob/master/UltimateChat-Spigot/src/main/java/br/net/fabiozumbi12/UltimateChat/Bukkit/UChat.java

Your UltimateChat plugin is likely out of date.
