### ISSUE TITLE
Sponge? 

### ISSUE THREAD

**Issue by DFameYT** [Scarsz/DiscordSRV#311]
Will this Plugin work on sponge/forge servers

**Comment by merjilin** [comment]
Not yet, no. DiscordSRV2 is in the works which will support Spigot, bungee, forge and sponge.

**Comment by VankkaGithub** [comment]
@merjilin Forge support was dropped https://github.com/Scarsz/DiscordSRV2/commit/a7f84535fb289ffddabd661774441eb45e3ee85c

**Comment by DFameYT** [comment]
What about sponge

**Comment by VankkaGithub** [comment]
that's going to be in DiscordSRV2

**Comment by Eufranio** [comment]
For now: https://github.com/Eufranio/MagiBridge

**Comment by VankkaGithub** [comment]
Dupe of https://github.com/Scarsz/DiscordSRV/issues/30

**Comment by DFameYT** [comment]
Looking forward to the DiscordSRV2? Any idea of a release date

**Comment by VankkaGithub** [comment]
some day. no eta really

**Comment by Scarsz** [comment]
There is no ETA for DiscordSRV2.
