### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by CoolLord22** [Scarsz/DiscordSRV#315]
Every time this user tries linking their account, it sends the following to console:
`[21:05:55 ERROR]: [DiscordSRV] [JDA] One of the EventListeners had an uncaught exception
[21:05:55 ERROR]: [DiscordSRV] [JDA] java.lang.NullPointerException`
The bot doesn't message her back, and it doesn't change her nickname, and it doesn't add the specified role either. If she tries to verify again, it says the account is already linked. When I use /discord linked <her name> it says it's linked too. When I try to unlink, it throws the following:
https://pastebin.com/kh2v9eGg

**Comment by CoolLord22** [comment]
That's legit the only thing console output for the first error, nothing before and nothing after. And that's weird because they are in the server in regards to second error. Anywho, I restarted the server and it all worked fine. I'll make sure to update in case it happens again!

**Comment by Scarsz** [comment]
Closing until able to reproduce
