### ISSUE TITLE
Channel placeholder for discord to minecraft

### ISSUE THREAD

**Issue by SaitDev** [Scarsz/DiscordSRV#317]
Please parse ingame channel's placeholder on setting `DiscordToMinecraftChatMessageFormat` if avaible instead of only `ChatChannelHookMessageFormat`

Reason: `%channelcolor%` on `ChatChannelHookMessageFormat` will be useless if we have some color on `DiscordToMinecraftChatMessageFormat` too

**Comment by Scarsz** [comment]
I don't get what your reasoning behind this is

**Comment by SaitDev** [comment]
sorry for not clear enough.
discordsrv have placeholer to help message has same color as ingame chat: `ChatChannelHookMessageFormat: "%channelcolor%%message%"`

but if we r also using `%toprolecolor%` : `DiscordToMinecraftChatMessageFormat: %toprolecolor%%username% » %message%` 

the final message discordsrv parsing will be: `%channelcolor%%toprolecolor%%username% » %message%`
which mean `%channelcolor%` cant effect **%message%** but `%toprolecolor%` does

**Comment by Scarsz** [comment]
Not possible due to the way code flows in the current version of DiscordSRV, potentially a fix for this with v2

**Comment by Scarsz** [comment]
Duplicate of #254
