### ISSUE TITLE
Recent issue with guild ID ????

### ISSUE THREAD

**Issue by CoolLord22** [Scarsz/DiscordSRV#336]
not entirely sure what's happening here but whenever the server status thing updates
The part with like "2/10 players online | 315 unique players ever joined | Server online for 120 minutes | Last update: Fri, 13. Apr 2018 20:18:27 EDT" it throws an error. here's the debug paste!
https://debug.scarsz.me/9133f67f-567d-4357-b7dd-064662ab5268

**Comment by CoolLord22** [comment]
Edit: After restarting the server a few times it's stopped *shrug*

**Comment by Scarsz** [comment]
Someone broke something at Discord with the API, has been fixed already

![jake response](https://scarsz.me/i/u4b4g.png)
