### ISSUE TITLE
Don't load plugin

### ISSUE THREAD

**Issue by NonoxSoux** [Scarsz/DiscordSRV#338]
I have thermos 1.7.10 and not can't load the plugin, this is the error

https://pastebin.com/u5iWWYSS

Please help me! u_u

**Comment by VankkaGithub** [comment]
Do not use plugman to restart/reload the plugin, restart your server

If the issue presists join Discord: https://scarsz.me/discord

**Comment by NonoxSoux** [comment]
The problem persists, I have restarted the server but it does not load.
I'm in discord, in which channel should I ask for help? Thank you

**Comment by VankkaGithub** [comment]
#support

**Comment by Scarsz** [comment]
The error given is caused by PlugMan. We don't support PlugMan.

If you want additional explanations, you need to post more errors.
