### ISSUE TITLE
Things like ingame item editors need me to put something in chat to edit a value, but it broadcasts in the server chat to everyone, but not ingame.

### ISSUE THREAD

**Issue by ThatOneJose95** [Scarsz/DiscordSRV#352]
We sometimes use NBT editors to edit stuff and they have plugin built-in editors or GUIs, and sometimes when we need to put a value, we have to put something in chat for it to recognize wich always broadcasts in server chat but never to everybody in chat. I use the latest version on 1.12.2

For example, if a plugin gives you the option of modifying a item's name and you need to put it in chat, I put "&dVoid Sword" and it doesn't show to anybody ingame, but in the discord server chat, it is put there. Any fixes to this?

**Comment by VankkaGithub** [comment]
That's not a issue on DiscordSRV's end the plugin author(s) of those plugins need to cancel the messages instead of (likely) just making the recipient list empty

**Comment by ThatOneJose95** [comment]
Oh... Ok, thanks for clearing it out. Ill contact them.

**Comment by Scarsz** [comment]
`discordsrv.chat` toggles if your chat is sent to Discord or not
