### ISSUE TITLE
Linked of authority in two places

### ISSUE THREAD

**Issue by HirokinWorld** [Scarsz/DiscordSRV#353]
Forever
I was looking for ways to cooperate with authority, but it does not work. Could anyone tell me? If possible, I hope in Japanese.

**Comment by Androkai** [comment]
Sorry, most of us don't speak Japanese. @ucchyocean , another great developer translated DiscordSRV for us into English. Maybe he's in the mood to help you. Else we have to do it in English.

To your problem: I'm not sure what you mean with "authority". Is it a plugin you're using or do you mean one of DiscordSRV's features? Please give us a hint.

**Comment by ucchyocean** [comment]
@HirokinWorld さん、
日本語での受け答えが必要であれば、私が応対いたしますので、日本語の質問内容も併記してください。
（二箇所での権限の共通化？とは、何について聞いていますか？）

**Comment by Scarsz** [comment]
Closing due to no response
