### ISSUE TITLE
Linking accounts

### ISSUE THREAD

**Issue by RedZephon** [Scarsz/DiscordSRV#38]
Link the accounts for the reasons (minecraft to discord)

**Comment by Androkai** [comment]
Collected idea about and expand by "Private messaging system"-topic as a suggestion:

`/discord link <username#1234>`
Link your Discord-account with your Minecraft-account. Using this the bot will send a private message to your Discord-account asking to confirm linking. Answer them with `!link <MCplayername>` to accept.

**Private messaging system:**
Now you're able to send private messages from Discord to Minecraft by sending a private message to the bot using `!msg <MCplayername> <message>`. Ingame users are able to answer to the latest message by using `/discord reply <message>` or sending messages to other linked users by using `/discord msg <username#1234> <message>` (you can use auto completion of Discord-usernames by using Tab-key).
Writing from ingame to non-linked Discordusers is only allowed with special permission to prevent spamming. Possible additions are muting of users/players within Minecraft or Discord. Writing with non-linked accounts from Discord to Minecraft isn't intended.

**Commands:**
`/discord link <username#1234>`
`/discord linklist` - show all Discord-accounts linked with this one
`/discord unlink <username#1234/all>` - remove link for specific/all Discord-accounts
`/discord reply <message>` or short `/discord r <message` or shorter `/dr <message>`
`/discord msg <username#1234> <message>` or `/discord pm ...` or `/discord tell ...` or `/dmsg ...` or ...

`!link <mcname>`
`!unlink <mcname>`
`!msg <playername> <message>` or `!pm <playername> <message>`
`!list`

**Comment by Scarsz** [comment]
https://github.com/Scarsz/DiscordSRV/commit/7f02f0fb80376513891f9dfc9df476375c51ba17
