### ISSUE TITLE
Discord Bot Token

### ISSUE THREAD

**Issue by kiyoshi-kurosaki** [Scarsz/DiscordSRV#4]
Hey, can you please add login with token function, but i created a Discord Bot with the Official Discord API and now just can login with a token :)

Regards Kiyo

**Comment by Scarsz** [comment]
It's not completely supported with JDA yet, going to switch to tokens when things become more supported, likely 8.1-9

**Comment by Scarsz** [comment]
https://github.com/Scarsz/DiscordSRV/commit/478f65abc95b0e835fbf9dbe193bbc8fe278e2d8
