### ISSUE TITLE
JDA Socket Disconnected

### ISSUE THREAD

**Issue by digimbyte** [Scarsz/DiscordSRV#43]
recently noticed this error on the server console
Using kCauldron 1.7.10 for Spigot/Forge

> [11:00:28 WARN]: [11:00:28] [Fatal] [JDARequester]: Encountered an exception:
> [11:00:28 WARN]: com.mashape.unirest.http.exceptions.UnirestException: java.net.UnknownHostException: discordapp.com
> [11:00:28 WARN]:        at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
> [11:00:28 WARN]:        at com.mashape.unirest.request.BaseRequest.asString(BaseRequest.java:56)
> [11:00:28 WARN]:        at com.scarsz.discordsrv.jda.requests.Requester.exec(Requester.java:92)
> [11:00:28 WARN]:        at com.scarsz.discordsrv.jda.requests.Requester.post(Requester.java:57)
> [11:00:28 WARN]:        at com.scarsz.discordsrv.jda.entities.impl.TextChannelImpl$AsyncMessageSender$Runner.run(TextChannelImpl.java:505)
> [11:00:28 WARN]: Caused by: java.net.UnknownHostException: discordapp.com
> [11:00:28 WARN]:        at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
> [11:00:28 WARN]:        at java.net.InetAddress.getAllByName(InetAddress.java:1192)
> [11:00:28 WARN]:        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
> [11:00:28 WARN]:        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
> [11:00:28 WARN]:        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111)
> [11:00:28 WARN]:        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
> [11:00:28 WARN]:        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
> [11:00:28 WARN]:        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
> [11:00:28 WARN]:        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
> [11:00:28 WARN]:        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
> [11:00:28 WARN]:        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
> [11:00:28 WARN]:        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
> [11:00:28 WARN]:        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
> [11:00:28 WARN]:        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
> [11:00:28 WARN]:        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
> [11:00:28 WARN]:        at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:138)

**Comment by Scarsz** [comment]
This is your server's DNS failing to resolve http://discordapp.com. It's a momentary error until your DNS works again, nothing can be done about this

**Comment by Carbonixx** [comment]
Yea its not momentary, once it happens it doesnt stop

**Comment by Scarsz** [comment]
> Yea its not momentary, once it happens it doesnt stop

Don't necro someone else's issue, ask for help in our Discord server
