### ISSUE TITLE
Capital letter issue Colors.json

### ISSUE THREAD

**Issue by loetje165** [Scarsz/DiscordSRV#49]
The colors.json file does not allow capital letters.
When you do put them in they are not registered as a capital letter but as a normal letter.

I was told that this issue was supposed to be fixed, however I have not yet been able to get it working with the latest snapshot.

Input would be "[Admin]" output is "[admin]"

Thanks for your time :)

**Comment by Androkai** [comment]
Two different suggestions:

1.) remove `.toLowerCase()` and make the user pay attention for lower case color codes
2.) add a second file `roleprefix.json` for use as `%toproleprefix%` in `config.yml` 

Example for 2.:
Role: `Admin`
Roleprefix: `A`
Rolecolor: `&c`
Output: `%toprolecolor%%toproleprefix% &r● &b%message%`

**Comment by Androkai** [comment]
Works. Good job!
