### ISSUE TITLE
Put a zero-width space in %username% and %displayname% to prevent ping spam.

### ISSUE THREAD

**Issue by TheReverend403** [Scarsz/DiscordSRV#50]
If a user has the same discord name as their Minecraft username, any message they send from Minecraft to Discord will (by default) ping that user if they are in a channel with the bot.

Obviously this is not ideal, so I propose putting a [zero-width space](https://en.wikipedia.org/wiki/Zero-width_space) before each character in the string before doing token replacements on %username% and %displayname%. This way, the username will appear normal on both ends of the link, but users shouldn't be pinged because the zero-width spaces cause the string to be different.

**Comment by Androkai** [comment]
How does your Discord-chat look like? There must be an `@` in front of the username to get the user pinged in Discord!?

**Comment by TheReverend403** [comment]
Ah yes, my mistake. A message had an @ in it that I didn't notice.
