### ISSUE TITLE
Option to enable bot changing nickname, rather than appending username in message.

### ISSUE THREAD

**Issue by WACOMalt** [Scarsz/DiscordSRV#54]
Hi there. I did a little research and I think this should be possible. Basically. the idea would be let the bot change its nickname instead of putting "Username: " in front of the message. It could change for every message echoed to be the name of the person talking.   It looks like discord limits nickname changes to 1800 times an hour, which for most servers would be plenty.

My goal here is that I need certain commands to be the first thing in the message for another bot to react to. So instead of "WACOMalt: !playlist"  it needs to see just "!playlist". the only way I can think of making this work is this solution, or getting the other dev to add support for commands in the middle of the messages.  (Which I'm also pushing for).

Would love to hear feedback on the idea. I'm sure there's more insight you guys could offer than I have been able to find.

**Comment by Scarsz** [comment]
not possible
