### ISSUE TITLE
PlaceholderAPI Support

### ISSUE THREAD

**Issue by InfinityAspire** [Scarsz/DiscordSRV#57]
Simple request, adding [PlaceholderAPI](https://www.spigotmc.org/resources/placeholderapi.6245/) support for the likes of formatting etc.

**Comment by Scarsz** [comment]
I see no point of it, truthfully, give some usage examples

**Comment by InfinityAspire** [comment]
Being able to set exactly what you want displayed in discord chat, at least prefix wise when using a multiple prefix system

**Comment by Scarsz** [comment]
As in actual screenshots/text representations of how it would look

**Comment by InfinityAspire** [comment]
Okay, I use PowerfulPerms to manage groups and PlaceholderAPI to show prefixes. Currently DiscordSRV only gets one of those prefixes to display in Discord which is [PR-IT]. Not even my primary group.
With PlaceholderAPI and formatting options in DiscordSRV, I could set it to be;
%powerfulperms_prefix_donator%%powerfulperms_prefix_misc%%powerfulperms_prefix_default% %player_displayname%
which would in turn show;
[$][PR-IT][Admin] Sequacious
as my name

**Comment by Scarsz** [comment]
Might work on this soon, we'll see

https://www.spigotmc.org/wiki/hooking-into-placeholderapi/

**Comment by Scarsz** [comment]
https://github.com/Scarsz/DiscordSRV/commit/f2511ecbd9a178cbaeb0a276f4711a4d1ded316b
https://github.com/Scarsz/DiscordSRV/commit/c346102f313fedcd112a7086c7c45c261d5391a4
