### ISSUE TITLE
PurpleIRC Support

### ISSUE THREAD

**Issue by InfinityAspire** [Scarsz/DiscordSRV#58]
Request to add [PurpleIRC](https://www.spigotmc.org/resources/purpleirc.2836/) support (maybe even work with that dev?) so that chat messages are shown from Discord ->IRC and vice versa

**Comment by Scarsz** [comment]
This is something that should be implemented into PurpleIRC, not DiscordSRV. @cnaude

**Comment by cnaude** [comment]
Challenge accepted!

**Comment by cnaude** [comment]
Latest dev build of PurpleIRC now hooks into DiscordSRV: https://h.cnaude.org/jenkins/job/PurpleIRC-spigot/241/

**Comment by Scarsz** [comment]
Impressive speed, nice work.
