### ISSUE TITLE
Wrong unique Playercounter on modserver

### ISSUE THREAD

**Issue by Denaris01** [Scarsz/DiscordSRV#63]
![wrongconuter](https://cloud.githubusercontent.com/assets/22527229/18963720/5e242258-8676-11e6-8f21-02de0cfe4937.jpg)

For the discord "unique players joined" the plugin count all files in payerdata. but on a modpackserver the mods itself make own files from each player. on my server are 3 players joined. but discordsrv says 13.
you must only count the .dat files from minecraft itself to work.

**Comment by Scarsz** [comment]
whoops

**Comment by Denaris01** [comment]
Great. Thanks xD

**Comment by Scarsz** [comment]
https://github.com/Scarsz/DiscordSRV/commit/6d48fe2c7f739435f8b3063aea915771d7b4f03e#diff-8c10cc3883e94c0b6d0a092b925343faR58
