### ISSUE TITLE
Venturechat filter integration 

### ISSUE THREAD

**Issue by rosedragon** [Scarsz/DiscordSRV#64]
Hello,

It seems discordsrv do not have compatibility with venturechat filter. While in game venture chat censor bad words people use, they will still appear bad words on discord. Here is sample:
I type in game: discordsrv chat filter test: asssprinkle in which in game will get filtered for bad words and display this instead:
http://image.prntscr.com/image/42ca735bdd044c50ad5bd7601fe68ddb.png
But yet in the discord chat it show the actual word:
http://image.prntscr.com/image/1f91277c3207453c8751a5c1aaa9281d.png

**Comment by Androkai** [comment]
https://github.com/Scarsz/DiscordSRV/commit/5275e7141d57b586acc46424e014ff3585f8ad7d https://github.com/Scarsz/DiscordSRV/commit/99858880ad25532273add0a2e614d6d0afd73b0e
