### ISSUE TITLE
Join/Leave messages not showing up

### ISSUE THREAD

**Issue by Vankka2** [Scarsz/DiscordSRV#72]
Disabling that the join messages not coming to discord (config option)

and ranks not showing on join
config:
MinecraftPlayerJoinMessageEnabled: true
MinecraftPlayerJoinMessageFormat: "[+] **%displayname%**"
MinecraftPlayerLeaveMessageEnabled: true
MinecraftPlayerLeaveMessageFormat: "[-] **%displayname%**"
in discord:
[+] user
[-] [Member] user

------------------------------------

When users have /OP the join and leave messages don't show up in discord (GroupManager)

**Comment by Androkai** [comment]
You can disable silent join by denying permissions like described here: https://github.com/Scarsz/DiscordSRV/wiki#when-i-joinquit-my-server-a-message-isnt-sent-in-the-chat-channel-for-me-what-gives
I think we will not implement a config option to disable this. I understand that handling permissions isn't very easy for the first time but for a good server it's a must have to know about and doing it this way is the better way. Correct me if I'm wrong.

***

You use `%displayname%` which is set by plugins like Essentials and DiscordSRV only grab this so if you wish to have this fixed you must report this to the developers of the plugin you're using for. We can't fix this within DiscordSRV, sorry :)

**Comment by Vankka2** [comment]
okay thx

**Comment by Vankka2** [comment]
^^^^^ can you read that real quick?

**Comment by Androkai** [comment]
In the moment I closed it the editing was missing.
I use these permissions with PermissionsEx and ensure you that it's working, also if you're OP. To help you I need more information about what plugins you're using, how they are configured and what permissions are set.

**Comment by Vankka2** [comment]
I am using GroupManager as soon as i deopped myself it showed up in Discord :)

**Comment by Vankka2** [comment]
Sorry for the edit

**Comment by Androkai** [comment]
No problem. Has GroupManager a config.yml? Maybe it's possible to set up overwriting of OP.

**Comment by Vankka2** [comment]
ohw let me check

**Comment by Eufranio** [comment]
GroupManager is very bad, use PermissionsEX

**Comment by Vankka2** [comment]
that seems to be a thing   
```
config:
    # With this enabled anyone set as op has full permissions when managing GroupManager
    # The user will be able to promote players to the same group or even above.
    opOverrides: true
```

**Comment by Vankka2** [comment]
that didn't fix it tho

**Comment by Androkai** [comment]
Please zip your GroupManger folder and send it to me.

**Comment by Vankka2** [comment]
hold on got to transfer it to my pc first :D

**Comment by Vankka2** [comment]
[GroupManager.zip](https://github.com/Scarsz/DiscordSRV/files/505044/GroupManager.zip)

**Comment by Vankka2** [comment]
Yes its a modded server btw (FTB Infinity evolved)

**Comment by Androkai** [comment]
You said you tried to remove the permissions like I said in the second post here. Can you re-add this to the config so I can find out if this is set correctly?

**Comment by Vankka2** [comment]
add what to the config?

**Comment by Androkai** [comment]
This one: https://github.com/Scarsz/DiscordSRV/wiki#when-i-joinquit-my-server-a-message-isnt-sent-in-the-chat-channel-for-me-what-gives

**Comment by Scarsz** [comment]
Closing because issue is not related to DiscordSRV

**Comment by Vankka2** [comment]
How about the config option for disabling that?

**Comment by Scarsz** [comment]
No. DiscordSRV will no longer jack permissions from other plugins, use `discordsrv.silentjoin` and `discordsrv.silentquit` in the dev builds onwards.

**Comment by Vankka2** [comment]
okay thx :)
