### ISSUE TITLE
Add access to variables for canned responses

### ISSUE THREAD

**Issue by Psi0991** [Scarsz/DiscordSRV#73]
Allowing access to variables in canned responses would enable more dynamic custom commands.
The more information accessible from the Minecraft server (and plugins) the better.

That would also allow users to write their own "playerlist" command if so desired and also display other information to any user.

**Comment by Scarsz** [comment]
Would you have some recommendations for what variables would be wanted?

**Comment by Tisawesomeness** [comment]
Use [PlaceholderAPI](https://www.spigotmc.org/resources/placeholderapi.6245/). It's godlike. You can even add your own placeholders to the plugin if you want.

**Comment by Scarsz** [comment]
🙄
