### ISSUE TITLE
Canned response triggers should not be caps sensitive

### ISSUE THREAD

**Issue by callmemantas** [Scarsz/DiscordSRV#76]
### Example

So this is what my current configuration file looks like:

``` yaml
DiscordCannedResponses: {"!ip": "mc.example.com"}
```

And let’s say Jon wants the server IP. He types `!Ip`. But nothing happens. Everything looks fine and diddly so Jon pings me and I have to explain to him that canned responses are caps sensitive. Isn’t that mildly annoying?
### Conclusion

This issue can be temporarily fixed by adding multiple triggers with different capitalization that do the same thing, but this is a pretty awful solution:

``` yaml
DiscordCannedResponses: {"!ip": "mc.example.com", "!Ip": "mc.example.com", "!IP": "mc.example.com", "!iP": "mc.example.com"}
```

I’m pretty sure most people expect this kind of behavior from bots anyways. And if that’s not the case you could just make this an option in the configuration file.

**Comment by Scarsz** [comment]
https://github.com/Scarsz/DiscordSRV/commit/09cd0bee5fff37ecac873732f8b7fe83d6757f81
