### ISSUE TITLE
Server offline channel topics

### ISSUE THREAD

**Issue by xXBuilderBXx** [Scarsz/DiscordSRV#79]
Hey could you add a config option to disable changing the channel topic so that it does not change it at all
Also when the server shutdowns can you make the channel topic say Server Offline or add another config options for it :)

**Comment by Scarsz** [comment]
As per the config if you clear the channel topic option the channel topic
updater won't start

**Comment by Eufranio** [comment]
And about the Server Offline status?

**Comment by Scarsz** [comment]
Later
