### ISSUE TITLE
Length limit

### ISSUE THREAD

**Issue by PretoAlbino** [Scarsz/DiscordSRV#80]
[Server] WARN [DiscordSRV] Tried sending message with length of 2244 (244 over limit)

Everytime I try to send a message in MC this appears, and I can't send in Discord to MC too.

**Comment by Eufranio** [comment]
Discord services were down, you probably received the cloudflare page.

**Comment by Scarsz** [comment]
@PretoAlbino show screenshots of what you mean please

**Comment by Scarsz** [comment]
Marking as invalid & closing because this issue hasn't been explained
