### ISSUE TITLE
Group -> Role synchronization

### ISSUE THREAD

**Issue by Scarsz** [Scarsz/DiscordSRV#96]

**Comment by gerd2002** [comment]
How does it currently work? is there a command/config/etc?

**Comment by Scarsz** [comment]
@gerd2002 https://github.com/Scarsz/DiscordSRV/blob/96f3dd766270c9843ccc8617ba1688da64311e03/src/main/resources/config.yml#L294-L300

**Comment by Androkai** [comment]
Works good but some things needs to be optimized:
- Catching exeptions:
  - **jda.core.exceptions.PermissionException** "The Discord bot's role needs to be on the first/top place in the roles list"
  - **java.lang.IllegalArgumentException** "You can't link a Minecraft group with the @everyone role" <-- can be checked at config-reading

The PermissionsEx hook listen for a onCommand event and check the players group then. Problem is that the group switch is done after this. Possible solution could be decreasing monitoring level for the event but needs testing.

Other permission plugins not tested.

**Comment by Scarsz** [comment]
@Androkai need stack traces to fix things

**Comment by Androkai** [comment]
@Scarsz https://gist.github.com/Androkai/fcd0ef5a41e18a7d016245ea9e22bd07

**Comment by Sarfraz787** [comment]
- [Thu 12:48:13 ERROR DiscordSRV] Group synchronization failed: Vault classes couldn't be found (did it enable properly?). Vault is required for synchronization to work.
![d](https://user-images.githubusercontent.com/103172416/162138943-87423d17-bb07-431b-8d44-9486ac053417.PNG)


How to solve this?

**Comment by Vankka** [comment]
Install Vault. If you need further help join https://discord.discordsrv.com

Locking, as this ticket is resolved & support is handled through Discord.
